version: "3.9"
services:
  couchdb:
    container_name: couchdb
    image: bitnami/couchdb:latest
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    expose:
      - 5984
    ports:
      - "5984:5984"
    volumes:
      - couchdb:/opt/couchdb/data

  mssql:
    container_name: mssql
    build:
      context: infastruction/Mssql
      dockerfile: dockerfile
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_PASSWORD}
      - MSSQL_PID=Express
    expose:
      - 1433
    ports:
      - "1433:1433"
    volumes:
      - mssql:/var/opt/mssql

  entryservice:
    container_name: entryservice
    build:
      context: .
      dockerfile: src/Server/EntryService/dockerfile
    environment:
    - AuthenticationSettings__JwtSecret=${JWT_SECRET}
    - DalSettings__ConnectionString=${COUCHDB_CONNECTION_STRING}
    - DalSettings__Username=${COUCHDB_USER}
    - DalSettings__Password=${COUCHDB_PASSWORD}
    expose:
    - 8001
    depends_on:
    - couchdb
    restart: unless-stopped

  goalservice:
    container_name: goalservice
    build:
      context: .
      dockerfile: src/Server/GoalService/dockerfile
    environment:
    - AuthenticationSettings__JwtSecret=${JWT_SECRET}
    - DalSettings__ConnectionString=${COUCHDB_CONNECTION_STRING}
    - DalSettings__Username=${COUCHDB_USER}
    - DalSettings__Password=${COUCHDB_PASSWORD}
    expose:
    - 8002
    depends_on:
    - couchdb
    restart: unless-stopped

  userservice:
    container_name: userservice
    build:
      context: .
      dockerfile: src/Server/UserService/dockerfile
    environment:
    - AuthenticationSettings__JwtSecret=${JWT_SECRET}
    - DalSettings__ConnectionString=${MSSQL_CONNECTION_STRING}
    - AdminSettings__AdminUsername=${ADMIN_USERNAME}
    - AdminSettings__AdminPassword=${ADMIN_PASSWORD}
    expose:
    - 8000
    depends_on:
    - mssql
    restart: unless-stopped

  app:
    container_name: app
    build:
      context: .
      dockerfile: src/App/dockerfile
    expose:
    - 80
    depends_on:
    - entryservice
    - goalservice
    - userservice
    restart: unless-stopped

  proxy:
    container_name: proxy
    image: nginx:alpine
    volumes:
    - ./config/proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
    - "80:80"
    - "443:443"
    depends_on:
    - entryservice
    - goalservice
    - userservice
    - app
    restart: unless-stopped

volumes:
  couchdb:
    external: true
  mssql:
    external: true