version: "3.9"
services:
  entryservice:
    container_name: entryservice
    build:
      context: .
      dockerfile: src/Server/EntryService/dockerfile
    environment:
    - JWT_SECRET="${JWT_SECRET}"
    expose:
    - 8001
    restart: unless-stopped

  goalservice:
    container_name: goalservice
    build:
      context: .
      dockerfile: src/Server/GoalService/dockerfile
    environment:
    - JWT_SECRET="${JWT_SECRET}"
    expose:
    - 8002
    restart: unless-stopped

  userservice:
    container_name: userservice
    build:
      context: .
      dockerfile: src/Server/UserService/dockerfile
    environment:
    - JWT_SECRET="${JWT_SECRET}"
    - ADMIN_USERNAME="${ADMIN_USERNAME}"
    - ADMIN_PASSWORD="${ADMIN_PASSWORD}"
    expose:
    - 8000
    restart: unless-stopped

  app:
    container_name: app
    build:
      context: .
      dockerfile: src/App/dockerfile
    expose:
    - 80
    restart: unless-stopped

  proxy:
    container_name: proxy
    image: nginx:alpine
    volumes:
    - ./config/proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
    - "80:80"
    restart: unless-stopped