FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY . /src
WORKDIR "/src/."
RUN dotnet build -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "src/App/WalkTrack.App/WalkTrack.App.csproj" -c Release -o /app/publish

FROM nginx:alpine
EXPOSE 80
COPY config/app/nginx.conf /etc/nginx/nginx.conf
COPY --from=publish /app/publish/wwwroot /usr/share/nginx/html
COPY config/app/appsettings.json /usr/share/nginx/html